[package]
name = "ls-rs"
version = "0.1.0"
authors = ["T Prajwal Prabhu <prajwalprabhu.tellar@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion=""
